### ISSUE TITLE
Assets Missing

### ISSUE THREAD

**Issue by mshamza28** [VRatPolito/CET-VR#1]
One of the required assets, "Race Tracks" is no longer available on the Unity Assets Store. Due to this Unity is unable to build the project.

**Comment by DavideCalandra** [comment]
Thank you very much for your interest in the Cybersickness Evaluation Testbed VR (CET-VR) repository and for bringing this issue to our attention. I apologize for the inconvenience you encountered with the unavailable "Race Tracks" asset.

Unfortunately, the Unity EULA does not allow us to publish Asset Store packages, even if they are free, as part of our open-source project. To address this issue in the long term, we are planning to replicate the asset with custom content, which will allow us to include it in the repository.

In the meantime, you could try to reach out to the original asset creator, Abdul Rahim (which e-mail address is still available through WaybackMachine: [https://web.archive.org/web/20210730115143/https://assetstore.unity.com/publishers/23148,](https://web.archive.org/web/20210730115143/https://assetstore.unity.com/publishers/23148) and ask if he can send you the asset package directly outside of the Asset Store.

Please note that a similar issue might arise with the Viking Village asset, as Unity recently replaced the previous version used in CET-VR with a new URP version. This could cause some issues because Unity may have changed the structure of the components, and the rest of the testbed is built for the Built-In Render Pipeline (whereas the new Viking Village is URP-only). Please let me know if you encounter these issues.
